---
title: ""
author: ""
# date: March 22, 2005
output: 
  revealjs::revealjs_presentation:
    self_contained: true
    css: styles.css
    # reveal_plugins: ["zoom", "menu"]
    reveal_options:
      width: 960
      height: 768
      slideNumber: true
      controls: false
bibliography: references.bib
csl: abnt.csl
---

```{r include=FALSE}

library(visNetwork)
library(kableExtra)

```

<center>UNIVERSIDADE FEDERAL DE MINAS GERAIS</center>
<center><medium>Centro de Desenvolvimento e Planejamento Regional</medium></center>

<br>

<center>CIÊNCIA DE DADOS PARA ESTUDOS EM INOVAÇÃO</center>

<br>

<center>Módulo: **Cienciometria e análise de patentes**</center>

<br>

<center>Semestre 2022/1</center>

<br>

<center>Professor: Rodrigo Fileto Cuerci Maciel</center>

# Objetivos desta aula

-   Apresentar funcionalidades do aplicativo [VOSviewer](https://www.vosviewer.com/){target="_blank"};

-   Apresentar um exemplo de análise de dados em cienciometria através do R.

# Material de aula

O Material desta aula bem como *scripts* utilizados encontram-se em [repositório aberto no Github](https://github.com/rodfileto-ufmg/ciencia_dados_inova/tree/main/03_cienciometria){target="_blank"}.

# Coleta de dados

Para as análises tanto no VOSviewer quanto no R utilizaremos dados coletados na Web of Science (WoS). É necessário subscrição para este recurso cujo acesso pode ser realizado através do Portal Capes.

# Estratégias de coleta

-   Tópico (Ex: "Complex Network");
-   Periódico (Ex: "Econometrica");
-   Agência de financiamento (EX: CAPES OR "Coordenação de Aperfeiçoamento de Pessoal de Nível Superior");
-   Dentre outros.

Para os objetivos desta aula sugere-se coletar cerca de 4000 documentos no formato "plain text" incluindo as referências citadas.

# VOSviewer

-   Ferramenta desenvolvida para análise de dados bibliométricos. Possui API integrado para coleta de dados (*Microsoft Academic*, *CrossRef* e *Europe PMC*). Mais detalhes consultar as referências desta apresentação [@vaneck2010; @vaneck2011; @vaneck2017] bem como o [manual do usuário](https://www.vosviewer.com/documentation/Manual_VOSviewer_1.6.17.pdf){target="_blank"}.

-   Também pode ser utilizada para visualização e análise de outros tipos de rede.

# Cienciometria no R

-   [BiblioMetrix](https://www.bibliometrix.org/){target="_blank"}: fornece instrumentos para elaboração de análises bibliométricas [@aria2017].
-   Ou então, a partir das ferramentas disponíveis, pode-se elaborar uma nova análise. O [conjunto de scripts](https://github.com/rodfileto-ufmg/ciencia_dados_inova/tree/main/03_cienciometria/scripts){target="_blank"} presentes no repositório da disciplina elabora uma análise de ligação bibliográfica seguindo, em linhas gerais, os princípios elaborados por Waltman et. al. [-@waltman2020].

# REFERÊNCIAS
