library(OECD)
# library(WDI)
library(tidyverse)
library(ggplot2)

# getOption('timeout')
# options(timeout=200)

#### Dados da OECD ####

# https://data.oecd.org/

dataset_OECD <- get_datasets()

gov_expenditure <- get_dataset("GBARD_NABS2007", start_time = 2020, end_time = 2020)

# Sempre checar estrutura de dados para identificar variáveis de interesse

GERD_gdp <- get_dataset("MSTI_PUB", start_time = 2020, end_time = 2021,
                        filter = "G_PPP+G_NC+G_XGDP+G_PPPCT+G_GRO+G_XPOP+G_CVXGDP+G_BRXGDP+TP_RS+TP_RSGRO+TP_RSXLF+TP_RSXEM+TP_TT+TP_TTGRO+TP_TTXLF+TP_TTXEM+G_FBXGDP+G_FGXGDP+G_XFB+G_XFG+G_XFON+G_XFA+G_XEB+G_XEH+G_XEG+G_XEI+TH_RS+TH_WRS+TH_WRXRS+BH_RS+BH_WRS+BH_WRXRS+GH_RS+GH_WRS+GH_WRXRS+HH_RS+HH_WRS+HH_WRXRS+B_PPP+B_NC+B_XGDP+B_PPPCT+B_GRO+B_XVA+BP_RS+BP_RSGRO+BP_RSXRS+BP_RSXEI+BP_TT+BP_TTGRO+BP_TTXTT+BP_TTXEI+B_FBCT+B_FBGRO+B_FBXVA+B_XFB+B_XFG+B_XFON+B_XFA+B_DRUG+B_XDRUG+B_COMP+B_XCOMP+B_AERO+B_XAERO+B_SERV+B_XSERV+H_PPP+H_NC+H_XGDP+H_PPPCT+H_GRO+H_XFB+HP_RS+HP_RSGRO+HP_RSXRS+HP_TT+HP_TTGRO+GV_PPP+GV_NC+GV_XGDP+GV_PPPCT+GV_GRO+GV_XFB+GP_RS+GP_RSGRO+GP_RSXRS+GP_TT+GP_TTGRO+C_PPP+C_NC+C_PPPCT+C_DFXTT+C_CVXTT+C_ECOPPP+C_ECOXCV+C_HEAPPP+C_HEAXCV+C_EDUPPP+C_EDUXCV+C_SPAPPP+C_SPAXCV+C_NORPPP+C_NORXCV+C_GUFPPP+C_GUFXCV+P_TRIAD+P_PCT+P_XTRIAD+P_ICTPCT+P_BIOPCT+TD_XDRUG+TD_IDRUG+TD_EDRUG+TD_BDRUG+TD_XCOMP+TD_ICOMP+TD_ECOMP+TD_BCOMP+TD_XAERO+TD_IAERO+TD_EAERO+TD_BAERO+ECON+PI+PPP-C+GDP+GDP_PPP+VA+VA_PPP+TOTPOP+ALF+TOTEMP+INDEMP.AUS+AUT+BEL+CAN+CHL+COL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LTU+LVA+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+EU27_2020+OECD+NMEC+ARG+CHN+ROU+RUS+SGP+ZAF+TWN",
                        pre_formatted = TRUE)


patent_by_tech <- get_dataset("PATS_IPC", 
                              filter = "EPO_A+USPTO_G+FAMILIES+PCT_A+EPO_G+USPTO_A+IP5.INVENTORS+APPLICANTS.AUS+AUT+BEL+CAN+CHL+COL+CRI+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LTU+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+OECD+WLD+NMEC+DZA+AND+ARG+ARM+BLR+BMU+BIH+BRA+BGR+CYM+CHN+HRV+CUB+CYP+DJI+ECU+EGY+SLV+GEO+GTM+HKG+IND+IDN+IRN+JAM+JOR+KAZ+KEN+PRK+KWT+LBN+LIE+MYS+MLT+MDA+MCO+MNG+MAR+MKD+NGA+PAK+PAN+PER+PHL+PRI+ROU+RUS+SAU+SYC+SGP+ZAF+LKA+TWN+THA+TTO+TUN+UKR+ARE+URY+UZB+VEN+ZWE+FRME+YUG.TOTAL+TOTAL_EST+BIOTECH+ICT+AI+NANOTECH+MEDICAL+PHARMA+ENV_TECH+WIPO_TECH+WIPO_11+WIPO_14+WIPO_17+WIPO_18+A61K+C12N+H.PRIORITY+APPLICATION+GRANT",
                              start_time = 2020, end_time = 2020, pre_formatted = TRUE)

